version: '3'

services:
  roundcubemail:
    image: roundcube/roundcubemail:latest
    container_name: roundcubemail
    ports:
      - 9002:80
    environment:
      - VIRTUAL_HOST=webmail.reservofficer.se
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=webmail.reservofficer.se
      - LETSENCRYPT_EMAIL=digitalocean@prosapio.se
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_SKIN=elastic
    volumes:
      - ./www:/var/www/html
      - ./db/sqlite:/var/roundcube/db
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external:
      name: nginx-proxy
